### ISSUE TITLE
Grpc echo server docker image for Arm based chip

### ISSUE THREAD

**Issue by akrambek** [aklivity/zilla-examples#31]
**Goal**

We want to set up the following Kubernetes example  `zilla grpc proxy` -> `Grpc Echo server` for the grpc.proxy example.

**Problem**
I have created https://github.com/akrambek/grpc-echo repo for grpc echo server which is based on Spring Boot. However, the problem I faced is to build the image for arm based chip since `protobuf-maven-plugin` doesn't have arm based executable yet. To get the idea I have pushed the to this branch https://github.com/akrambek/zilla-examples/tree/feature/grpc-kafka/grpc.proxy

```
FROM  maven:3.9.0-eclipse-temurin-17-alpine

RUN apk upgrade --no-cache && \
    apk add --no-cache libgcc libstdc++ ncurses-libs && \
    apk add --no-cache libgcc nodejs git

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk

RUN apk add --force-overwrite glibc-2.35-r0.apk

WORKDIR /usr/app

RUN git clone https://github.com/akrambek/grpc-echo.git
RUN cd grpc-echo && mvn install

ENTRYPOINT ["java", "-jar", "grpc-echo/target/echo-develop-SNAPSHOT.jar"]
```

```
#10 33.54 [INFO] Compiling 1 proto file(s) to /usr/app/grpc-echo/target/generated-sources/protobuf/java
#10 33.66 [ERROR] PROTOC FAILED: qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
#10 33.66
#10 33.66 [ERROR] /usr/app/grpc-echo/src/main/resources/proto/echo.proto [0:0]: qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
`maven:3.9.0-eclipse-temurin-17-alpine
```

**Alternative**

Perhaps, we can find an alternative solution, for example, using the go I found a couple of them but I didn't have enough time to try them out and the ones I found were not maintained for a long time.

**Comment by vordimous** [comment]
fixed by https://github.com/aklivity/zilla-examples/pull/145
