### ISSUE TITLE
The http.filesystem example fails for https requests

### ISSUE THREAD

**Issue by drymus** [aklivity/zilla-examples#57]
Steps to reproduce:

1. Change directly into the http.filesystem example director
2. Run the `./setup` command
3. Run `curl --cacert test-ca.crt https://localhost:9090/index.html`

*Expected behavior:*
Curl is able to fetch the the `index.html` file.

*Observed behavior:*
Curl exits with the following output:
`curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)`

**Comment by jfallows** [comment]
@drymus resolved issue with etag header in https://github.com/aklivity/zilla/issues/551, please verify with local `develop-SNAPSHOT` build or release `0.9.56` or later.
