### ISSUE TITLE
http.filesystem curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla-examples#90]
Using the tls curl command results in an error

```
http.filesystem % curl --cacert test-ca.crt https://localhost:9090/index.html
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**Comment by vordimous** [comment]
It works when manually set to http1.1:
```
curl --cacert test-ca.crt https://localhost:9090/index.html --http1.1
<html>
<head>
<title>Welcome to Zilla!</title>
</head>
<body>
<h1>Welcome to Zilla!</h1>
</body>
</html>

```

**Comment by vordimous** [comment]
This may also be the issue happening in the sse.proxy.jwt example https://github.com/aklivity/zilla-examples/issues/92#issuecomment-1783431248

**Comment by jfallows** [comment]
@vordimous  resolved issue with `etag` header in https://github.com/aklivity/zilla/issues/551, please verify.

**Comment by vordimous** [comment]
> @vordimous resolved issue with `etag` header in [aklivity/zilla#551](https://github.com/aklivity/zilla/issues/551), please verify.

Tested the `http.filesystem` example and didn't run into this error.
